apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.container.frontEndName }}-ingress
  namespace: {{ .Values.container.namespace }}
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/target-type: instance
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/group.name: venture-alb-ingress-group
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.container.frontEndName }}-service
            port:
              number: {{ .Values.container.frontEndServicePort }} 
        