apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.container.frontEndName }}-ingress
  namespace: {{ .Values.container.namespace }}
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/target-type: instance
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/group.name: venture-alb-ingress-group
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:285104104520:certificate/3dcd4a0d-5d39-41a1-b657-34e624196ac7
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.container.frontEndName }}-service
            port:
              number: {{ .Values.container.frontEndServicePort }} 
        