apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.container.frontEndName }}-service
  labels:
    app: {{ .Values.label.name }}
  namespace: {{ .Values.container.namespace }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
spec:
  selector:
    app: {{ .Values.container.frontEndName }}
  type: NodePort
  ports:
    - protocol: TCP
      port: {{ .Values.container.frontEndServicePort }} 
      targetPort: {{ .Values.container.frontEndPort }}
