name: CI

env:
  ECR_REPOSITORY_URI: 285104104520.dkr.ecr.us-east-1.amazonaws.com/venture-industries-laboratory

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install / Lint / Test / Build
        run: |
          npm i && \
          npm run test && \
          npm run build \

      - name: Create Image / Push to ECR
        run: |
          docker login -u AWS -p $(aws ecr get-login-password) ${ECR_REPOSITORY_URI} && \
          docker build -t "${ECR_REPOSITORY_URI}:latest" . && \
          docker push "${ECR_REPOSITORY_URI}:latest" && \
          docker image prune -f
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v2
      - name: Helm Deploy
        run: |
          sudo apt-get install curl && \
          curl -o kubectl https://amazon-eks.s3-us-west-2.amazonaws.com/1.20.4/2021-04-12/bin/linux/amd64/kubectl && sudo mv kubectl /usr/local/bin/kubectl && \
          curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C ./ && sudo mv eksctl /usr/local/bin && \
          curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | sudo bash && \
          eksctl utils write-kubeconfig --cluster venture-compound-east && \
          helm upgrade -i venture-industries venture-industries
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
